package com.fst.backend.dto.mapper;

import com.fst.backend.dto.request.OrderItemRequest;
import com.fst.backend.dto.response.OrderItemResponse;
import com.fst.backend.persistence.entity.OrderItemEntity;
import org.springframework.stereotype.Component;

@Component
public class OrderItemMapper {

    public OrderItemResponse toResponse(OrderItemEntity orderItemEntity) {
        return new OrderItemResponse(
                orderItemEntity.getProduct().getId(),
                orderItemEntity.getQuantity(),
                orderItemEntity.getPrice()
        );
    }

    public OrderItemEntity toEntity(OrderItemRequest orderItemRequest) {
        return new OrderItemEntity(
                null, // generated by the database
                null, // set in the service layer
                orderItemRequest.getQuantity(),
                orderItemRequest.getPrice()
        );
    }
}
